travis:
  secure:
    BINSTAR_TOKEN: N2aomYkJfmWv507E1xJtKB/z+jqOBI//u8cDDV3DJpN/RqGysleycBgFmGfcDypyMgzOAdBnrwTp/SpfD9ZKhMABlGiw0hgz8nYkbiZDT0N/bbdOT0x0wnq4tlpB8gMlUoIUxfsMJyMFKXbSDrtphe80GKeK+QfVZ+V1JgIXsksY90wnXxpyZfeimmakCs/IhrLmGaWNlohXJ3X21W0f09k56OhlfkFU4I9EdNl8f0IJ1KOF3b8a4CoGWdz1r0492q0Xtd+UwMvpyP0IcOF/8AsmVFkD15aA/RJQ/K3Ol96384HhVy0D21uBrU5kJL7D/AwDxEW98syEuzFr4z33T8xF4jEbAY8Fk/jtacge6F8HCflnXG/Hy6tl3IMxVhgab7YVV94su8Nrgzqv0yGRXjvHKjqQ0fBsIgH1AA6Nzgu8cAQmZ87hQ8UVkih5Vg4Nnc89Q/NQdJotpyyVt6UoThdxdKDHIWoK7nSwoGyC0p3HnMGsUjFqRVMGrffyu7uBvDEUZHfoeYgOm8x0qYADLbrm3P3skWyPHTid/8zYbmUel0dK5X3KFOGdqVOHOot++AUUvZ/6w//xYFnSQDsO8j5RuE7EL/SwOpmQOyzYl/i8ZAatp2/fbKLPJBafwlQFuT9xZagw4b/nmStET6uo/8/mrrkGeF5Aw5S7SZat2Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
